### ISSUE TITLE
C# Loader Error

### ISSUE THREAD

**Issue by Tanner555** [pixeltris/USharp#1]
I notice that using a normal pre-compiled version of ue4, I had to put the usharp plugin inside my game project folder (create a folder called "Plugins" inside your root game project folder and paste usharp inside there). When I enabled the plugin and restarted the editor, I got a C# Loader Error.
![usharploadererror](https://user-images.githubusercontent.com/17560348/46240377-5af13e80-c35b-11e8-809d-efd9b40ba98e.PNG)
Apparently the c# loader was expecting a "UnrealEngine.Runtime" dll inside the Managed Folder. The problem is that the Managed folder didn't exist at all. So I had to manually create the "Managed" folder under "USharp/Binaries/". Then I looked inside each project inside the UnrealEngine.Runtime folder, looked inside the bin/Debug folder, and copy-pasted the dlls and pdbs from these folders inside the Managed folder I just created. Now the plugin loads just fine with no errors. The build process should create these dlls in the appropriate places by default.

**Comment by Tanner555** [comment]
I fixed the C# Loader Error with this pull request https://github.com/pixeltris/USharp/pull/4.

This pr https://github.com/pixeltris/USharp/pull/3 includes the PCHUsage var fix.

**Comment by pixeltris** [comment]
I agree a some kind of build process should exist. It might be worth creating a small build tool which builds the C++ USharp project, the managed projects and puts everything where it needs to be. It might be useful to also create a custom csproj which does the build event to invoke the AssemblyRewriter rather than having a post-build event as required at the moment for C# game project files.

**Comment by Tanner555** [comment]
pull request #4 is now merged 👍
