### ISSUE TITLE
Missing Engine Module ApexDestruction

### ISSUE THREAD

**Issue by Darkkitten** [pixeltris/USharp#85]
Missing an Engine Module  ApexDestruction as the title suggests.

**Comment by Tanner555** [comment]
I think it's always a great idea to document issues and missing features like these. Good job 😄 

There's a lot more modules missing besides ApexDestruction. If you look inside the ModulesWhitelist text file inside the USharp/Settings directory, you'll find a bunch of modules that are whitelisted. You can try adding in the module you wish to use, exactly as it would be spelled. And then open up your Unreal project and type 'USharpGen modules' in the command window. See if that adds the missing module back in. If there's a Blacklist file in your settings folder as well, make sure to open it up and check to see if your missing module is there.

That would be awesome if you could document all the missing modules you've encountered so that we could potentially try to add them in. But try adding them in through the whitel

**Comment by pixeltris** [comment]
Currently the [whitelist](https://github.com/pixeltris/USharp/blob/master/Settings/ModulesWhitelist.txt) only contains core modules (none of the engine plugins). There are still a lot of issues with the code generator so I decided to go with using a whitelist rather than a blacklist for now (to avoid people running into compilation issues).

@Tanner555 described the process of adding new modules perfectly. There is also a Wiki page about this now https://github.com/pixeltris/USharp/wiki/Generating-wrappers-for-Cpp-game-code.

I will accept a PR for any module that anyone wants to add (ApexDestruction included), just make sure it compiles without any issues and it's all good to go!
